goog.provide('app.Map');

app.Map = [[
	{type:'treem'}, {},             {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},             {type:'treem'}, {},             {type:'treem'}, {},             {type:'grass'}, {type:'pathv'}, {type:'treem'}, {},             {type:'treem'}, {},             {type:'treem'}, {}, {type:'treem'}, {}, {type:'treem'}, {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {},               {},               {},               {},               {},               {},               {},               {},             {},             {},             {type:'treem'}, {},             {type:'grass'}, {type:'pathv'}, {},             {type:'treem'}, {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {type:'wall'},    {type:'wallEnd'}, {type:'wallEnd'}, {type:'wallEnd'}, {type:'wallEnd'}, {type:'wallEnd'}, {type:'wall'},    {type:'treem'}, {},             {},             {},             {},             {},             {type:'pathv'}, {},             {},             {type:'treem'}, {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {type:'wall'},    {type:'grass'},   {type:'grass'},   {type:'grass'},   {type:'grass'},   {type:'grass'},   {type:'wall'},    {},             {},             {},             {},             {},             {},             {type:'pathv'}, {},             {},             {},             {},             {},             {}, {},             {}, {type:'treem'}, {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {type:'wall'},    {type:'grass'},   {type:'house'},   {type:null},      {type:null},      {type:'grass'},   {type:'wall'},    {},             {},             {},             {},             {},             {},             {type:'pathv'}, {},             {},             {type:'treem'}, {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{type:'treem'}, {},             {type:'wall'},    {type:'grass'},   {type:null},      {type:null},      {type:null},      {type:'grass'},   {type:'wallEnd'}, {},             {},             {},             {},             {},             {},             {type:'pathv'}, {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{type:'treem'}, {},             {type:'wallEnd'}, {type:'grass'},   {type:null},      {type:null},      {type:null},      {type:'grass'},   {},               {},             {},             {},             {},             {type:'treem'}, {},             {type:'pathv'}, {},             {},             {},             {},             {},             {}, {type:'treem'}, {}, {},             {}, {}              ],[
	{type:'treem'}, {},             {type:'treem'},   {},               {},               {type:'pathv'},   {},               {},               {},               {},             {},             {},             {},             {},             {},             {type:'pathv'}, {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{type:'treem'}, {},             {type:'treem'},   {},               {},               {type:'pathv'},   {type:'pathh'},   {type:'pathh'},   {type:'pathh'},   {type:'pathh'}, {type:'pathh'}, {type:'pathh'}, {type:'pathh'}, {type:'pathh'}, {type:'pathh'}, {type:'pathv'}, {type:'treem'}, {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {},               {},               {},               {type:'pathv'},   {type:'grass'},   {type:'grass'},   {},               {},             {},             {},             {},             {},             {type:'treem'}, {type:'pathv'}, {type:'treem'}, {},             {type:'grass'}, {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {type:'treem'},   {},               {},               {type:'pathv'},   {},               {},               {type:'treem'},   {},             {},             {},             {},             {},             {},             {type:'treem'}, {},             {},             {},             {type:'grass'}, {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{},             {},             {},               {},               {},               {type:'pathv'},   {},               {},               {},               {},             {},             {},             {},             {},             {},             {},             {},             {type:'grass'}, {type:'grass'}, {},             {},             {}, {type:'treem'}, {}, {type:'treem'}, {}, {type:'treem'}  ],[
	{type:'pathh'}, {type:'pathh'}, {type:'pathh'},   {type:'pathh'},   {type:'pathh'},   {type:'pathv'},   {type:'treem'},   {},               {},               {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {},             {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},               {},               {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{},             {},             {},               {},               {},               {},               {type:'treem'},   {},               {},               {},             {},             {type:'grass'}, {},             {},             {},             {},             {},             {type:'treem'}, {},             {type:'treem'}, {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{},             {},             {},               {},               {},               {type:'grass'},   {},               {},               {},               {},             {},             {type:'grass'}, {},             {},             {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{},             {},             {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},               {},               {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  
]];

// app.Map = [[
// 	{}, {}, {}              ],[
// 	{}, {}, {type:'treem'}  ],[
// 	{}, {}, {}             
// ]];
