goog.provide('app.Map');

app.Map = [[
	{type:'treem'}, {}, {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},             {type:'treem'}, {},             {type:'treem'}, {}, {type:'grass'}, {type:'grass'}, {type:'treem'}, {},             {type:'treem'}, {},             {type:'treem'}, {}, {type:'treem'}, {}, {type:'treem'}, {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {},               {},               {},               {},               {},               {},               {},               {},             {},             {},             {type:'treem'}, {}, {type:'grass'}, {type:'grass'}, {},             {type:'treem'}, {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {type:'wall'},    {type:'wallEnd'}, {type:'wallEnd'}, {type:'wallEnd'}, {type:'wallEnd'}, {type:'wallEnd'}, {type:'wall'},    {type:'treem'}, {},             {},             {},             {}, {},             {},             {},             {},             {type:'treem'}, {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {type:'wall'},    {type:'grass'},   {type:'grass'},   {type:'grass'},   {type:'grass'},   {type:'grass'},   {type:'wall'},    {},             {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {type:'treem'}, {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {type:'wall'},    {type:'grass'},   {type:'house'},   {type:null},      {type:null},      {type:'grass'},   {type:'wall'},    {},             {},             {},             {},             {}, {},             {},             {},             {},             {type:'treem'}, {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{type:'treem'}, {}, {type:'wall'},    {type:'grass'},   {type:null},      {type:null},      {type:null},      {type:'grass'},   {type:'wallEnd'}, {},             {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{type:'treem'}, {}, {type:'wallEnd'}, {type:'grass'},   {type:null},      {type:null},      {type:null},      {type:'grass'},   {},               {},             {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {type:'treem'}, {}, {},             {}, {}              ],[
	{type:'treem'}, {}, {type:'treem'},   {},               {},               {},               {},               {},               {},               {type:'treem'}, {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{type:'treem'}, {}, {type:'treem'},   {},               {},               {},               {},               {},               {},               {},             {},             {},             {},             {}, {type:'treem'}, {},             {type:'treem'}, {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {},               {},               {},               {},               {type:'grass'},   {type:'grass'},   {},               {},             {},             {},             {},             {}, {type:'treem'}, {},             {type:'treem'}, {},             {type:'grass'}, {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {type:'treem'},   {},               {},               {},               {},               {},               {type:'treem'},   {},             {},             {},             {},             {}, {},             {type:'treem'}, {},             {},             {},             {type:'grass'}, {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{},             {}, {},               {},               {},               {},               {},               {},               {},               {},             {},             {},             {},             {}, {},             {},             {},             {type:'grass'}, {type:'grass'}, {},             {},             {}, {type:'treem'}, {}, {type:'treem'}, {}, {type:'treem'}  ],[
	{},             {}, {},               {},               {type:'treem'},   {},               {type:'treem'},   {},               {},               {},             {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{type:'treem'}, {}, {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},               {},               {},             {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {}              ],[
	{},             {}, {},               {},               {},               {},               {type:'treem'},   {},               {},               {},             {},             {type:'grass'}, {},             {}, {},             {},             {},             {type:'treem'}, {},             {type:'treem'}, {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{},             {}, {},               {},               {},               {type:'grass'},   {},               {},               {},               {},             {},             {type:'grass'}, {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  ],[
	{},             {}, {type:'treem'},   {},               {type:'treem'},   {},               {type:'treem'},   {},               {},               {},             {},             {},             {},             {}, {},             {},             {},             {},             {},             {},             {},             {}, {},             {}, {},             {}, {type:'treem'}  
]];